Homework
plasmatrip/go_final_project pull request #1
Opened 2024-06-27 14:18 UTC by plasmatrip

2024-06-28 14:27 UTC, just-musha requested changes
Антон, привет! 

Оставляю комментарии по 1 итерации ревью.

2024-06-28 14:27 UTC, just-musha commented on README.md
> +var Token = `"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJoYXNoIjoiNTk5NDQ3MWFiYjAxMTEyYWZjYzE4MTU5ZjZjYzc0YjRmNTExYjk5ODA2ZGE1OWIzY2FmNWE5YzE3M2NhY2ZjNSJ9.EKlvvMlZ450BVUO__owlT3mkJ2NnhMIMr_OdXFzl95U"`
Для учебного задания ок. Но в идеале не нужно коммитить токен в репозиторий, тк это мб не безопасно. Лучше описать по шагам, как его сгенерить

2024-06-28 14:27 UTC, just-musha commented on README.md
> +TODO_DATE_LAYOUT=20060102
А для чего выносишь в переменные окружения? `TODO_DATE_LAYOUT` и `TODO_SEARCH_LAYOUT`

2024-06-28 14:27 UTC, just-musha commented on cmd/main.go
> +	configs.LoadEnv()
Полезно будет добавить логов - что происходит при запуске, 
и что сервер в итоге запусился - и на каком порту

2024-06-28 14:27 UTC, just-musha commented on repository/database.go
> +type Todo struct {
Лучше более говорящее название взять, например `Storage`, `Repository` 
Лучше по названию пакета

2024-06-28 14:27 UTC, just-musha commented on repository/database.go
> +
Лишняя пустя строчка

2024-06-28 14:27 UTC, just-musha commented on repository/delete.go
> +		return err
Лучше вернуть обернутую ошибку `fmt.Printtf("..... : %w", err)` (не критично)

2024-06-28 14:27 UTC, just-musha commented on repository/delete.go
> +		return err
(и в других методах этого уровня)

2024-06-28 14:27 UTC, just-musha commented on repository/insert.go
> +		log.Printf("ошибка получения id записи: %s", err.Error())
Вообще может быть полезным на уровне базы ошибки оборачивать и возвращать выше, а логировать уже выше уровнем - там где будет больше контекста об ошибке, и можно проследить откуда она происходит. Но так тоже ок, для задания не крит

2024-06-28 14:27 UTC, just-musha commented on service/service.go
> +	"sort"
Сортировка импортов - нужно разбить на блоки - стандартная библиотека, внешние пакеты и внутренние. Для сортировки в пределах блоков - `goimports` (вроде он сработал, но на блоки надо разбить руками)

2024-06-28 14:27 UTC, just-musha commented on service/service.go
> +	"sort"
Это нужно проверить и сделать во всех файлах

2024-06-28 14:27 UTC, just-musha commented on service/service.go
> +		if days > 400 {
Числа можно вынести в константы, чтоб не оставались как magic number в коде

2024-06-28 14:27 UTC, just-musha commented on configs/config.go
> +		if err := os.Mkdir(logDir, 0755); err != nil {
Как насчет здесь права тоже через спец. константы прописать? Как ниже

2024-06-28 14:27 UTC, just-musha commented on Dockerfile
> +COPY ./api ./api
Можно ли объединить в одну команду, чтобы не плодить слои?

2024-06-28 14:27 UTC, just-musha commented on repository/delete.go
> +		log.Printf("ошибка удаления данных: %s", err.Error())
Вижу что на уровне хендлера тоже логируешь ошибку. Тогда тут я бы предложила убрать логирование, и только обернуть ошибку. Она будет залогирована выше

2024-06-28 17:03 UTC, plasmatrip commented on README.md
> +TODO_DATE_LAYOUT=20060102
Согласен, решение корявое. Хотелось вынести шаблон из когда, чтобы иметь возможность его поменять и не лезть в код. Думаю неплохим решением будет вынести это в ямл конфиг, например. Но для этого учебного задания определю в гошном конфиге.

2024-06-28 17:03 UTC, plasmatrip commented on repository/database.go
> +
Убрал.

2024-06-28 17:21 UTC, plasmatrip commented on service/service.go
> +		if days > 400 {
Ок, согласен. Вынес в константы. Возможно даже слишком))

2024-06-28 18:42 UTC, plasmatrip commented on Dockerfile
> +COPY ./api ./api
Я погуглил и не нашел решения. Вот тут [https://stackoverflow.com/questions/37715224/copy-multiple-directories-with-one-command](url) пишут, что решения нет, кроме изменения структуры проекта - каталоги, которые необходимо скопировать, расположить в одном родительском каталоге, который копировать. Возможно я не прав.

2024-06-28 18:46 UTC, plasmatrip commented on README.md
> +var Token = `"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJoYXNoIjoiNTk5NDQ3MWFiYjAxMTEyYWZjYzE4MTU5ZjZjYzc0YjRmNTExYjk5ODA2ZGE1OWIzY2FmNWE5YzE3M2NhY2ZjNSJ9.EKlvvMlZ450BVUO__owlT3mkJ2NnhMIMr_OdXFzl95U"`
Абсолютно согласен, но в итоговом задании нет требований реализовать полноценную систему аутентификации, поэтому токен прописан в ридми. Исходя из постановки задачи, я не представляю, как можно описать получение токена без указания секрета, на котором он шифруется. При реализации полноценной системы аутентификации или SSO думаю такой проблемы не было бы.

2024-06-28 19:10 UTC, plasmatrip commented on repository/delete.go
> +		return err
Поправил.

2024-06-28 19:11 UTC, plasmatrip commented on repository/insert.go
> +		log.Printf("ошибка получения id записи: %s", err.Error())
Учту, в учебном проекте оставлю как есть.

2024-06-28 19:29 UTC, plasmatrip commented on service/service.go
> +	"sort"
Поправил.

2024-06-28 19:54 UTC, plasmatrip commented on repository/delete.go
> +		log.Printf("ошибка удаления данных: %s", err.Error())
Поправил. На слое репозитория убрал логирование, оставил на уровне апи.

2024-06-28 19:55 UTC, plasmatrip commented on configs/config.go
> +		if err := os.Mkdir(logDir, 0755); err != nil {
Сделал.

2024-06-28 19:55 UTC, plasmatrip commented on repository/database.go
> +type Todo struct {
Переименовал в Repository.

2024-06-28 20:50 UTC, plasmatrip commented on cmd/main.go
> +	configs.LoadEnv()
Сделал. До конфигурации логирования вывод лога идет стандартно в stdout, после загрузки переменных окружения лог направляется в файл.

2024-06-29 10:38 UTC, just-musha commented on README.md
> +TODO_DATE_LAYOUT=20060102
Поняла, ок!

2024-06-29 11:15 UTC, just-musha approved these changes
Поздравляю! Работа принята! Хороший сервис получился. Спасибо за твой подход к работе в целом, готовность быстро разбираться в деталях, быстро править. Успехов дальше в обучении и работе!

2024-06-29 11:15 UTC, just-musha commented on repository/repository.go
> +func NewToDo() *Repository {
```diff
-NewToDo
+NewRepository
```

2024-06-29 11:15 UTC, just-musha commented on service/service.go
> +		if days > 400 {
Топ!

2024-06-29 11:15 UTC, just-musha commented on Dockerfile
> +COPY ./api ./api
А, имела в виду примерно так сделать

`COPY ./cmd ./configs ./model ./repository ./service ./web /`

2024-06-29 11:20 UTC, plasmatrip commented on repository/repository.go
> +func NewToDo() *Repository {
Дааа. В спешке забыл))

2024-06-29 11:22 UTC, plasmatrip commented
> Поздравляю! Работа принята! Хороший сервис получился. Спасибо за твой подход к работе в целом, готовность быстро разбираться в деталях, быстро править. Успехов дальше в обучении и работе!

Спасибо за ревью и пожелания!

2024-07-02 14:25 UTC, merged